spring:
  application:
    name: ALMS

  datasource:
    url: jdbc:mysql://localhost:3306/ALM
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none

server:
  port: 8081

